backend:
  name: git-gateway
  branch: master

media_folder: static/img/uploads
public_folder: /img/uploads

site_url: https://knit2yarns.com

collections:
  - name: 'sessions'
    label: 'Classes'
    folder: 'markdown/sessions'
    create: true
    fields:
      - { label: 'Class Start Date', name: 'date', widget: 'datetime' }
      - { label: 'Image', name: 'image_url', widget: 'image', required: false }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - {
          label: 'Price',
          name: 'price',
          widget: 'number',
          value_type: 'int',
          min: 0
        }
      - {
          label: 'Price Details',
          name: 'price_details',
          widget: 'string',
          required: false,
        }
      - { label: 'Meta 1', name: 'meta_1', widget: 'string' }
      - { label: 'Meta 2', name: 'meta_2', widget: 'string' }
  - name: 'hero-images'
    label: 'Banner Images'
    folder: 'markdown/hero-images'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Image', name: 'image_url', widget: 'image' }
  - name: 'website-text'
    label: 'Website Text'
    delete: false
    files:
      - name: 'hero-text'
        label: 'Banner Text'
        file: 'markdown/hero-text.md'
        fields:
          - name: 'hidden'
            default: ''
            required: false
            widget: 'hidden'
          - label: 'Banner Text'
            name: 'body'
            widget: 'markdown'
            required: false
